# Generated by Django 5.0.4 on 2024-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Computing Equipment', 'Computing Equipment'), ('Audio-Visual Equipment', 'Audio-Visual Equipment'), ('Laboratory Equipment', 'Laboratory Equipment'), ('Workshop Tools', 'Workshop Tools'), ('Office Equipment', 'Office Equipment'), ('Educational and Teaching Aids', 'Educational and Teaching Aids'), ('Miscellaneous', 'Miscellaneous')], default='Computing Equipment', max_length=200),
        ),
    ]
