# Generated by Django 5.0.4 on 2024-04-28 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
