# Generated by Django 5.0.4 on 2024-04-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='product_name',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
